/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "java_study"
include("app")
include("app-kotlin")
include("ex01_hello")
include("ex02_oop_basic")
include("ex03_package")
include("ex04_collection")
include("ex05_swing_basic")
include("ex06_swing_event")
include("ex07_swing_thread")
include("ex08_serial_uart")

project(":ex01_hello").projectDir = file("examples/01_hello")
project(":ex02_oop_basic").projectDir = file("examples/02_oop_basic")
project(":ex03_package").projectDir = file("examples/03_package")
project(":ex04_collection").projectDir = file("examples/04_collection")
project(":ex05_swing_basic").projectDir = file("examples/05_swing_basic")
project(":ex06_swing_event").projectDir = file("examples/06_swing_event")
project(":ex07_swing_thread").projectDir = file("examples/07_swing_thread")
project(":ex08_serial_uart").projectDir = file("examples/08_serial_uart")
