/*
 * This source file was generated by the Gradle 'init' task
 */
package startup;

import org.junit.jupiter.api.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    void mainPrintsCurrentTime() {
        PrintStream originalOut = System.out;
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        try {
            System.setOut(new PrintStream(output, true, StandardCharsets.UTF_8));
            assertDoesNotThrow(() -> App.main(new String[0]));
        } finally {
            System.setOut(originalOut);
        }

        String line = output.toString(StandardCharsets.UTF_8).trim();
        assertTrue(
                line.matches("Current time: \\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}"),
                "unexpected output: " + line
        );
    }
}
