/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "startup.App"
}

tasks.register<JavaExec>("runEx01") {
    group = "application"
    description = "Runs basic.ex01"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("basic.ex01")
}

val weekPackages = mapOf(
    "01" to "basic",
    "02" to "arraymethod",
    "03" to "oop1",
    "04" to "oop2",
    "05" to "exceptionapi",
    "06" to "collection",
    "07" to "modernjava",
    "08" to "fileio",
    "09" to "threading",
    "10" to "network"
)

weekPackages.forEach { (week, pkg) ->
    (1..3).forEach { ex ->
        val exNo = ex.toString().padStart(2, '0')
        tasks.register<JavaExec>("runWeek${week}Ex${exNo}") {
            group = "application"
            description = "Runs $pkg.ex$exNo"
            classpath = sourceSets["main"].runtimeClasspath
            mainClass.set("$pkg.ex$exNo")
        }
    }
}

tasks.register<JavaExec>("runWeek01Ex04") {
    group = "application"
    description = "Runs basic.ex04"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("basic.ex04")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
